permalink: /:categories/:title.html
url: "http://gregisms.github.io/"
full_name: "Gregisms"
first_name: "Gregisms"
last_name: ""
blog_title: "Gregisms "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "gregisms"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Rants and raves"
twitter: "vectorvekar"
github: "vekar"


